const CONFIG={api:'https://script.google.com/macros/s/AKfycbzcTUCy-WsRkjFnGyiFB3n6Zbn2mq0sOrzrYojfx4wqWAWMBZef0Injsa_s_JIVoF-v/exec',sheetId:'1FMtcuixqhDZ7vPiEhhwsBmykRAkgoxOspDi9cDXohQ0',project:'การพัฒนาครูผู้ช่วยสู่การเป็นครูมืออาชีพ',year:'2569'};
const units=[
 {id:'U1',date:'19 กรกฎาคม 2569',time:'08.30–10.00 น.',title:'ศาสตร์พระราชาสู่แนวปฏิบัติและกฎหมายที่ครูควรรู้'},
 {id:'U2',date:'19 กรกฎาคม 2569',time:'10.00–12.00 น.',title:'การประยุกต์ใช้ปัญญาประดิษฐ์ในการจัดประสบการณ์และการเรียนการสอน'},
 {id:'U3',date:'19 กรกฎาคม 2569',time:'13.00–16.30 น.',title:'การจัดการเรียนการสอนในศตวรรษที่ 21'},
 {id:'U4',date:'20 กรกฎาคม 2569',time:'09.00–12.00 น.',title:'การบริหารงาน 4 ฝ่ายในสถานศึกษา'},
 {id:'U5',date:'20 กรกฎาคม 2569',time:'13.00–14.30 น.',title:'การสร้างแรงบันดาลใจและความก้าวหน้าในอาชีพครู'},
 {id:'U6',date:'20 กรกฎาคม 2569',time:'14.30–15.30 น.',title:'สิทธิประโยชน์ของข้าราชการครูและสวัสดิการ'}
];
const state={user:JSON.parse(localStorage.getItem('trainingUser')||'null'),font:+localStorage.getItem('fontSize')||16};
const content=document.querySelector('#content');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function notify(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
async function api(action,data={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(CONFIG.api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8','Accept':'application/json'},body:JSON.stringify({action,...data}),redirect:'follow',cache:'no-store',signal:ctl.signal});const text=await r.text();let j;try{j=JSON.parse(text)}catch(_){const hint=text.includes('<!DOCTYPE')||text.includes('<html')?'Apps Script ตอบกลับเป็นหน้า HTML โปรดตรวจ Deployment และสิทธิ์ “ทุกคน”':'API ไม่ได้ตอบกลับเป็น JSON';throw new Error(`${hint} (HTTP ${r.status})`)}if(!j.ok)throw new Error(j.message||'ดำเนินการไม่สำเร็จ');return j}catch(e){if(e.name==='AbortError')throw new Error('API ไม่ตอบกลับภายใน 15 วินาที');if(e instanceof TypeError)throw new Error('เบราว์เซอร์เชื่อมต่อ Apps Script ไม่ได้ โปรดตรวจ URL /exec, สิทธิ์ “ทุกคน” และส่วนขยายที่บล็อกเว็บไซต์');throw e}finally{clearTimeout(timer)}}
async function testApiConnection(){const btn=document.querySelector('#apiTestBtn');if(btn){btn.disabled=true;btn.textContent='กำลังตรวจ…'}try{const r=await fetch(`${CONFIG.api}?action=health&t=${Date.now()}`,{redirect:'follow',cache:'no-store'});const text=await r.text();let data;try{data=JSON.parse(text)}catch(_){throw new Error('URL ตอบกลับเป็น HTML หรือข้อความอื่น ไม่ใช่ API เวอร์ชันล่าสุด')}if(!data.ok||data.service!=='Teacher Development Training API')throw new Error('URL นี้ไม่ใช่ Backend ของระบบฉบับล่าสุด');Swal.fire('เชื่อมต่อสำเร็จ',`${data.service}<br>เวอร์ชัน ${data.version}`,'success')}catch(e){Swal.fire('เชื่อมต่อไม่ได้',e.message,'error')}finally{if(btn){btn.disabled=false;btn.textContent='ทดสอบการเชื่อมต่อ API'}}}
const pageTitle=(title,desc)=>`<div class="section-head"><div><span class="eyebrow" style="color:#2563eb">โครงการพัฒนาครูผู้ช่วย</span><h2>${title}</h2><p>${desc}</p></div></div>`;
function home(){return `<section class="hero"><span class="eyebrow">สำนักงานเขตพื้นที่การศึกษาประถมศึกษาสกลนคร เขต 2</span><h1>พัฒนาครูผู้ช่วย<br>สู่การเป็นครูมืออาชีพ</h1><p>ระบบบริหารจัดการการอบรม ประจำปีงบประมาณ พ.ศ. 2569 ระหว่างวันที่ 15–20 กรกฎาคม 2569</p><div class="actions"><a class="btn btn-light" href="#attendance">ลงเวลาเข้าอบรม</a><a class="btn btn-ghost" href="#status">ตรวจสอบสถานะ</a></div></section>
${pageTitle('ภาพรวมโครงการ','ข้อมูลล่าสุดของการอบรม')}<div class="grid four"><div class="card stat"><strong>53</strong><small>ผู้เข้ารับการอบรม</small></div><div class="card stat"><strong>6</strong><small>หน่วยการเรียนรู้</small></div><div class="card stat"><strong>2</strong><small>วันอบรม ณ สถานที่</small></div><div class="card stat"><strong>80%</strong><small>เกณฑ์ผ่าน Post-test</small></div></div>
${pageTitle('บริการสำหรับผู้เข้ารับการอบรม','เลือกบริการที่ต้องการ')}<div class="grid"><a class="card menu-card" href="#schedule"><span class="icon">◷</span><h3>กำหนดการอบรม</h3><p>ตรวจสอบวัน เวลา หัวข้อ และรายละเอียดการแต่งกาย</p></a><a class="card menu-card" href="#attendance"><span class="icon">✓</span><h3>ลงเวลาเข้าอบรม</h3><p>ลงเวลาด้วยรหัสประจำตัวหรือ QR Code</p></a><a class="card menu-card" href="#learning"><span class="icon">↗</span><h3>Learning Space</h3><p>ส่งลิงก์รายงานผลการอบรมระยะที่ 1</p></a><a class="card menu-card" href="#test"><span class="icon">✎</span><h3>แบบทดสอบ</h3><p>ทำ Pre-test และ Post-test ครบทั้ง 6 หัวข้อ</p></a><a class="card menu-card" href="#status"><span class="icon">◎</span><h3>สถานะการอบรม</h3><p>ติดตามรายการที่ดำเนินการแล้วและสิ่งที่ยังขาด</p></a><a class="card menu-card" href="#certificate"><span class="icon">▣</span><h3>เกียรติบัตร</h3><p>ตรวจสอบและดาวน์โหลดเมื่อผ่านเกณฑ์</p></a></div>`}
function schedule(){return pageTitle('กำหนดการอบรม','ระยะที่ 2 การเสริมสร้างสมรรถนะ ณ หอประชุมรวมใจสามัคคี')+`<div class="card" style="margin-bottom:16px"><span class="badge">ระยะที่ 1 · ออนไลน์</span><h3>Learning Space</h3><p>15–20 กรกฎาคม 2569 · พัฒนาจริยธรรมสำหรับเจ้าหน้าที่ของรัฐแรกบรรจุ</p></div><div class="timeline">${units.map((u,i)=>`<article class="session"><time>${u.date}<br><small>${u.time}</small></time><div><span class="badge">หน่วยที่ ${i+1}</span><h3>${u.title}</h3></div><button class="btn btn-ghost" style="color:#1d4ed8" onclick="showUnit('${u.id}')">รายละเอียด</button></article>`).join('')}</div><div class="card" style="margin-top:16px"><h3>ข้อมูลสำคัญ</h3><p>ลงทะเบียน 08.00–08.30 น. · พักอาหารว่าง 10.30–10.45 น. และ 14.30–14.45 น.</p><p><strong>19 กรกฎาคม:</strong> โทนขาว–ดำ กางเกงขายาวสีดำ &nbsp; <strong>20 กรกฎาคม:</strong> ชุดข้าราชการสีกากีคอพับแขนยาว รองเท้าคัชชูสีดำ</p></div>`}
function loginBox(action='login'){return `<form class="card form-card" id="lookupForm"><h3>ยืนยันตัวตนผู้เข้ารับการอบรม</h3><p>กรอกเลขที่จ่ายตรง 7 หลัก เพื่อเข้าถึงข้อมูลของท่าน</p><div class="field"><label for="personId">เลขที่จ่ายตรง</label><input id="personId" name="personId" inputmode="numeric" pattern="[0-9]{7}" maxlength="7" required placeholder="เช่น 0229789"></div><button class="btn" type="submit">ตรวจสอบข้อมูล</button></form>`}
function attendance(){return pageTitle('ลงเวลาเข้าอบรม','บันทึกเวลาแยกตามหน่วยการเรียนรู้')+`<div class="grid"><div class="card"><span class="badge ok">วิธีที่ 1</span><h3>ลงเวลาด้วยบัญชีผู้ใช้</h3><p>ยืนยันเลขที่จ่ายตรง แล้วเลือกหน่วยที่กำลังเปิดให้ลงเวลา</p><button class="btn" onclick="openAttendance()">เริ่มลงเวลา</button></div><div class="card"><span class="badge">วิธีที่ 2</span><h3>สแกน QR Code</h3><p>สแกนรหัสที่เจ้าหน้าที่แสดง ณ ห้องอบรม ระบบจะระบุหน่วยให้อัตโนมัติ</p><button class="btn btn-ghost" style="color:#1d4ed8" onclick="location.hash='attendance?scan=1'">กรอกรหัส QR</button></div><div class="card"><span class="badge warn">กรณีพิเศษ</span><h3>ให้เจ้าหน้าที่บันทึก</h3><p>ติดต่อจุดลงทะเบียนเมื่ออุปกรณ์มีปัญหา พร้อมแสดงบัตรประจำตัว</p></div></div>`}
function learning(){return pageTitle('รายงานผล Learning Space','ส่งหลักฐานการอบรมระยะที่ 1')+`<form class="card form-card" id="learningForm">${idField()}<div class="field"><label for="reportUrl">ลิงก์รายงานผล</label><input type="url" id="reportUrl" required placeholder="https://..."></div><div class="field"><label for="note">หมายเหตุ</label><textarea id="note" rows="3" maxlength="500"></textarea></div><button class="btn" type="submit">ส่งรายงานเพื่อตรวจ</button></form>`}
function test(){return pageTitle('แบบทดสอบก่อนและหลังการอบรม','แบบทดสอบครอบคลุม 6 หัวข้อ หัวข้อละ 5 ข้อ')+`<div class="grid"><div class="card"><span class="badge">Pre-test</span><h3>ทดสอบก่อนการอบรม</h3><p>ใช้วัดความรู้พื้นฐาน ไม่มีเกณฑ์คะแนนขั้นต่ำ แต่ต้องทำให้ครบ</p><button class="btn" onclick="startTest('pre')">เริ่มทำ Pre-test</button></div><div class="card"><span class="badge ok">Post-test</span><h3>ทดสอบหลังการอบรม</h3><p>ต้องได้คะแนนไม่น้อยกว่าร้อยละ 80 และส่งคำตอบครบทุกข้อ</p><button class="btn" onclick="startTest('post')">เริ่มทำ Post-test</button></div></div>`}
function idField(){return `<div class="field"><label for="personId">เลขที่จ่ายตรง</label><input id="personId" inputmode="numeric" pattern="[0-9]{7}" maxlength="7" required></div>`}
function status(){return pageTitle('ตรวจสอบสถานะการอบรม','ดูความก้าวหน้า คะแนน และคุณสมบัติการรับเกียรติบัตร')+loginBox('status')}
function certificate(){return pageTitle('ตรวจสอบเกียรติบัตร','ผู้ผ่านเกณฑ์สามารถดาวน์โหลดเกียรติบัตรได้ทันที')+`<form class="card form-card" id="certForm">${idField()}<div class="field"><label for="certNo">เลขที่เกียรติบัตร (ถ้ามี)</label><input id="certNo" maxlength="30"></div><button class="btn" type="submit">ตรวจสอบเกียรติบัตร</button></form>`}
function admin(){
  const session=JSON.parse(sessionStorage.getItem('adminSession')||'null');
  if(session?.token)return adminDashboard(session);
  return pageTitle('เข้าสู่ระบบผู้ดูแล','สำหรับผู้ดูแลระบบและเจ้าหน้าที่ที่ได้รับสิทธิ์')+`<form class="card form-card" id="adminLoginForm"><div class="field"><label for="adminUsername">ชื่อผู้ใช้</label><input id="adminUsername" name="username" autocomplete="username" required placeholder="เช่น admin"></div><div class="field"><label for="adminPassword">รหัสผ่าน</label><input type="password" id="adminPassword" name="password" autocomplete="current-password" required></div><div class="actions"><button class="btn" type="submit">เข้าสู่ระบบ</button><button class="btn btn-ghost" style="color:#1d4ed8" id="apiTestBtn" type="button" onclick="testApiConnection()">ทดสอบการเชื่อมต่อ API</button></div><p><small>ระบบจะเปรียบเทียบรหัสผ่านที่เข้ารหัส SHA-256 กับข้อมูลในชีต Users</small></p></form>`
}
function adminDashboard(session){return pageTitle(`ยินดีต้อนรับ ${esc(session.name)}`,`สิทธิ์การใช้งาน: ${esc(session.role)}`)+`<div class="grid four"><div class="card stat"><strong>53</strong><small>ผู้เข้ารับการอบรม</small></div><div class="card stat"><strong>0</strong><small>ผ่านเกณฑ์แล้ว</small></div><div class="card stat"><strong>0</strong><small>รอตรวจ Learning Space</small></div><div class="card stat"><strong>6</strong><small>หน่วยการเรียนรู้</small></div></div><div class="section-head"><div><h2>เครื่องมือผู้ดูแล</h2><p>เลือกงานที่ต้องการดำเนินการ</p></div><button class="btn btn-danger" onclick="adminLogout()">ออกจากระบบ</button></div><div class="grid"><a class="card menu-card" href="#admin-users"><h3>จัดการผู้ใช้งาน</h3><p>เพิ่ม แก้ไข ค้นหา และกำหนดสิทธิ์</p></a><a class="card menu-card" href="#admin-qr"><h3>จัดการ QR Code</h3><p>สร้างรหัสลงเวลาตามหน่วย</p></a><a class="card menu-card" href="#admin-report"><h3>รายงานและสถิติ</h3><p>กรองข้อมูลและส่งออก CSV</p></a></div>`}
function placeholder(name){return pageTitle(name,'ส่วนจัดการสำหรับเจ้าหน้าที่')+`<div class="empty card"><div class="icon">⚙</div><h3>กรุณาเข้าสู่ระบบเจ้าหน้าที่</h3><p>เมนูนี้ตรวจสอบสิทธิ์จาก Google Apps Script ก่อนแสดงข้อมูล</p><a class="btn" href="#admin">เข้าสู่ระบบ</a></div>`}
const pages={home,schedule,attendance,learning,test,status,certificate,admin,'admin-users':()=>placeholder('จัดการผู้ใช้งาน'),'admin-qr':()=>placeholder('จัดการ QR Code'),'admin-report':()=>placeholder('รายงานและสถิติ')};
function route(){let key=(location.hash.slice(1).split('?')[0]||'home');content.innerHTML=(pages[key]||home)();document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+key));document.querySelector('#nav').classList.remove('open');bindForms();scrollTo({top:0,behavior:'smooth'})}
function bindForms(){document.querySelector('#lookupForm')?.addEventListener('submit',lookup);document.querySelector('#learningForm')?.addEventListener('submit',submitLearning);document.querySelector('#certForm')?.addEventListener('submit',lookupCert);document.querySelector('#adminLoginForm')?.addEventListener('submit',adminLogin)}
async function adminLogin(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='กำลังตรวจสอบ…';try{const r=await api('login',{username:e.target.username.value.trim(),password:e.target.password.value});sessionStorage.setItem('adminSession',JSON.stringify(r.data));Swal.fire('เข้าสู่ระบบสำเร็จ',`ยินดีต้อนรับ ${r.data.name}`,'success').then(route)}catch(err){Swal.fire('เข้าสู่ระบบไม่สำเร็จ',err.message,'error')}finally{btn.disabled=false;btn.textContent='เข้าสู่ระบบ'}}
function adminLogout(){sessionStorage.removeItem('adminSession');notify('ออกจากระบบแล้ว');route()}
async function lookup(e){e.preventDefault();const id=e.target.personId.value;content.innerHTML='<div class="loading"><span></span><p>กำลังตรวจสอบข้อมูล…</p></div>';try{const r=await api('getStatus',{personId:id});renderStatus(r.data)}catch(err){renderDemoStatus(id,err.message)}}
function renderDemoStatus(id,warning){renderStatus({personId:id,name:'ผู้เข้ารับการอบรม',school:'—',attendance:0,pretest:false,posttestScore:null,learning:'รอส่ง',satisfaction:false,passed:false},warning)}
function renderStatus(d,warning=''){content.innerHTML=pageTitle('สถานะของ '+esc(d.name),esc(d.school||''))+(warning?`<div class="card" style="border-color:#fbbf24;margin-bottom:15px"><span class="badge warn">โหมดข้อมูลสำรอง</span><p>ยังเชื่อมต่อ API ไม่สำเร็จ: ${esc(warning)}</p></div>`:'')+`<div class="card"><div class="section-head"><div><h2>ความคืบหน้า ${d.attendance||0}/6 หน่วย</h2><p>เลขที่จ่ายตรง ${esc(d.personId)}</p></div><strong>${Math.round(((d.attendance||0)/6)*100)}%</strong></div><div class="progress"><i style="width:${((d.attendance||0)/6)*100}%"></i></div><div class="checklist"><div class="check">Learning Space <b>${esc(d.learning||'รอตรวจ')}</b></div><div class="check">ลงเวลาครบ 6 หน่วย <b>${d.attendance===6?'ผ่าน':'ยังไม่ครบ'}</b></div><div class="check">Pre-test <b>${d.pretest?'ครบ':'ยังไม่ครบ'}</b></div><div class="check">Post-test ≥ 80% <b>${d.posttestScore==null?'ยังไม่มีคะแนน':d.posttestScore+'%'}</b></div><div class="check">แบบประเมินความพึงพอใจ <b>${d.satisfaction?'ครบ':'ยังไม่ครบ'}</b></div><div class="check">ผลการอบรม <span class="badge ${d.passed?'ok':'warn'}">${d.passed?'ผ่าน':'อยู่ระหว่างดำเนินการ'}</span></div></div></div>`}
async function submitLearning(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await api('submitLearning',{personId:e.target.personId.value,url:e.target.reportUrl.value,note:e.target.note.value});Swal.fire('ส่งรายงานแล้ว','เจ้าหน้าที่จะตรวจสอบและแจ้งผลในระบบ','success');e.target.reset()}catch(err){Swal.fire('ยังส่งไม่ได้',err.message,'error')}finally{btn.disabled=false}}
async function lookupCert(e){e.preventDefault();try{const r=await api('getCertificate',{personId:e.target.personId.value,certNo:e.target.certNo.value});if(r.data?.url)location.href=r.data.url;else Swal.fire('ยังไม่พบเกียรติบัตร','โปรดตรวจสอบสถานะการผ่านอบรม','info')}catch(err){Swal.fire('ตรวจสอบไม่สำเร็จ',err.message,'error')}}
function openAttendance(){Swal.fire({title:'เลือกหน่วยการเรียนรู้',input:'select',inputOptions:Object.fromEntries(units.map((u,i)=>[u.id,`หน่วยที่ ${i+1}: ${u.title}`])),showCancelButton:true,confirmButtonText:'ดำเนินการต่อ',cancelButtonText:'ยกเลิก'}).then(r=>{if(r.isConfirmed)promptAttendance(r.value)})}
function promptAttendance(unitId){Swal.fire({title:'ยืนยันการลงเวลา',html:`<input id="swal-id" class="swal2-input" maxlength="7" inputmode="numeric" placeholder="เลขที่จ่ายตรง"><input id="swal-code" class="swal2-input" placeholder="รหัสจาก QR Code">`,confirmButtonText:'ลงเวลา',showCancelButton:true,preConfirm:()=>({personId:document.querySelector('#swal-id').value,code:document.querySelector('#swal-code').value})}).then(async r=>{if(r.isConfirmed){try{await api('checkIn',{unitId,...r.value});Swal.fire('ลงเวลาสำเร็จ','','success')}catch(e){Swal.fire('ลงเวลาไม่สำเร็จ',e.message,'error')}}})}
function startTest(type){Swal.fire('ยืนยันตัวตนก่อนเริ่มแบบทดสอบ','กรุณาเข้าสู่ระบบด้วยเลขที่จ่ายตรง เพื่อป้องกันการส่งคำตอบซ้ำ','info')}
function showUnit(id){const i=units.findIndex(u=>u.id===id),u=units[i];Swal.fire({title:`หน่วยที่ ${i+1}`,html:`<p>${esc(u.title)}</p><strong>${u.date} · ${u.time}</strong>`,confirmButtonText:'ปิด'})}
document.querySelector('#menuBtn').onclick=()=>{const n=document.querySelector('#nav');n.classList.toggle('open');document.querySelector('#menuBtn').setAttribute('aria-expanded',n.classList.contains('open'))};
document.querySelector('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark'))};
document.querySelector('#fontUp').onclick=()=>setFont(Math.min(20,state.font+1));document.querySelector('#fontDown').onclick=()=>setFont(Math.max(14,state.font-1));function setFont(n){state.font=n;document.documentElement.style.fontSize=n+'px';localStorage.setItem('fontSize',n)}
if(localStorage.getItem('dark')==='true')document.body.classList.add('dark');setFont(state.font);addEventListener('hashchange',route);addEventListener('DOMContentLoaded',route);
